import Stars from "./components/Stars";
import "./globals.css";
import { Orbitron, Plus_Jakarta_Sans } from "next/font/google";

const orbitron = Orbitron({ subsets: ["latin"], variable: "--font-orbitron" });
const plusJakarta = Plus_Jakarta_Sans({ subsets: ["latin"], variable: "--font-jakarta" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${orbitron.variable} ${plusJakarta.variable}`}>
      
        <body className="bg-black text-white">{children}</body>
      
      
    </html>
  );
}
